# Sonosite PSU Fixture
from Tkinter import *
import ttk
root=Tk()

result_row = 10
high_volt_row = 40

RAILS = ['Vin', '5P0_VD','12P0_VD', '5P0_VA', '3P3_VA', '5N0_VA', 'TRIPLE', '1P8_VA SW', '1P8_VA LDO',
         '1P8_VD SW', '1P8_VD LDO', '1P2_VD', '3P3_VD', '3P3_VSHIF', '10P0_SW', '10P0_VSHIF',
         '12P0_VSHIF', 'VTXP', 'VTXN', 'BIAS', 'VTXP_BIAS', 'VTXN_BIAS']


#-------------------------------------------------------------
# Section for Load Monitor and Control
#-------------------------------------------------------------
# Column 0: Labels
w=Label(root, justify=LEFT, text="#").grid(row=result_row, column=0)
w=Label(root, justify=LEFT, padx=10,text="RAIL").grid(row=result_row, column=1)
count_row=0
for count_col in RAILS:
    Label(text=count_row+1, relief=RAISED, width=3).grid(row=result_row + 1 + count_row, column=0)
    Label(text=count_col, relief=RAISED, width=10).grid(row=result_row + 1 + count_row, column=1)
    count_row = count_row + 1

#Colum 2: Enables
w=Label(root, justify=CENTER, padx=10,text="EN").grid(row=result_row, column=2)
load_a1 = IntVar()
load_a2 = IntVar()
w=Checkbutton(root, variable=load_a1, selectcolor="#DDD").grid(row=result_row+1, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+2, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+3, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+4, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+5, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+6, column=2)
w=Checkbutton(root, variable=load_a1, selectcolor="#DDD").grid(row=result_row+7, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+8, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+9, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+10, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+11, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+12, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+13, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+14, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+15, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+16, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+17, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+18, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+19, column=2)
w=Checkbutton(root, variable=load_a1).grid(row=result_row+20, column=2)
w=Checkbutton(root, variable=load_a1, selectcolor="#DDD").grid(row=result_row+21, column=2)
w=Checkbutton(root, variable=load_a1, selectcolor="#DDD").grid(row=result_row+22, column=2)

#Column 3: Power Good
w=Label(root, justify=LEFT, padx=10,text="PG").grid(row=result_row, column=3)
load_b1 = IntVar()
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+1, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+2, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+3, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+4, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+5, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+6, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+7, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+8, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+9, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+10, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+11, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+12, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+13, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+14, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+15, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+16, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+17, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+18, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+19, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+20, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+21, column=3)
w=Checkbutton(root, variable=load_b1, selectcolor="#0FF").grid(row=result_row+22, column=3)

#Column 4: Sync Enable
w=Label(root, justify=LEFT, padx=10,text="SYNC").grid(row=result_row, column=4)
load_b1 = IntVar()
w=Checkbutton(root, variable=load_b1).grid(row=result_row+1, column=4)
w=Checkbutton(root, variable=load_b1).grid(row=result_row+2, column=4)
w=Checkbutton(root, variable=load_b1).grid(row=result_row+3, column=4)
w=Checkbutton(root, variable=load_b1).grid(row=result_row+4, column=4)
w=Checkbutton(root, variable=load_b1).grid(row=result_row+5, column=4)
w=Checkbutton(root, variable=load_b1).grid(row=result_row+6, column=4)
w=Checkbutton(root, variable=load_b1).grid(row=result_row+7, column=4)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+8, column=4)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+9, column=4)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+10, column=4)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+11, column=4)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+12, column=4)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+13, column=4)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+14, column=4)
w=Checkbutton(root, variable=load_b1).grid(row=result_row+15, column=4)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+16, column=4)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+17, column=4)
w=Checkbutton(root, variable=load_b1).grid(row=result_row+18, column=4)
w=Checkbutton(root, variable=load_b1).grid(row=result_row+19, column=4)
w=Checkbutton(root, variable=load_b1).grid(row=result_row+20, column=4)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+21, column=4)
w=Checkbutton(root, variable=load_b1, selectcolor="#DDD").grid(row=result_row+22, column=4)

#Column 5: SYNC Frequency
w=Label(root, justify=RIGHT,text="FREQ").grid(row=result_row, column=5)
sync_freq1 = Entry(root, width=8)
sync_freq2 = Entry(root, width=8)
sync_freq3 = Entry(root, width=8)
sync_freq4 = Entry(root, width=8)
sync_freq5 = Entry(root, width=8)
sync_freq6 = Entry(root, width=8)
sync_freq7 = Entry(root, width=8)
sync_freq8 = Entry(root, width=8)
sync_freq9 = Entry(root, width=8)
sync_freq10 = Entry(root, width=8)
sync_freq11 = Entry(root, width=8)
sync_freq12 = Entry(root, width=8)
sync_freq13 = Entry(root, width=8)
sync_freq14 = Entry(root, width=8)
sync_freq15 = Entry(root, width=8)
sync_freq16 = Entry(root, width=8)
sync_freq17 = Entry(root, width=8)
sync_freq18 = Entry(root, width=8)
sync_freq19 = Entry(root, width=8)
sync_freq20 = Entry(root, width=8)
sync_freq21 = Entry(root, width=8)
sync_freq1.grid(row=result_row+1, column=5, sticky=W)
sync_freq2.grid(row=result_row+2, column=5, sticky=W)
sync_freq3.grid(row=result_row+3, column=5, sticky=W)
sync_freq4.grid(row=result_row+4, column=5, sticky=W)
sync_freq5.grid(row=result_row+5, column=5, sticky=W)
sync_freq6.grid(row=result_row+6, column=5, sticky=W)
sync_freq7.grid(row=result_row+7, column=5, sticky=W)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+8, column=5, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+9, column=5, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+10, column=5, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+11, column=5, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+12, column=5, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+13, column=5, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+14, column=5, sticky=E)
sync_freq15.grid(row=result_row+15, column=5, sticky=W)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+16, column=5, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+17, column=5, sticky=E)
sync_freq18.grid(row=result_row+18, column=5, sticky=W)
sync_freq19.grid(row=result_row+19, column=5, sticky=W)
sync_freq20.grid(row=result_row+20, column=5, sticky=W)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+21, column=5, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+22, column=5, sticky=E)

#Column 6: ADC Voltage Measurements
w=Label(root, justify=RIGHT,text="V_meas").grid(row=result_row, column=6)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#0FF").grid(row=result_row+1, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+2, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+3, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+4, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+5, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#0FF").grid(row=result_row+6, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+7, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+8, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+9, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+10, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+11, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+12, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+13, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+14, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+15, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#0FF").grid(row=result_row+16, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#0FF").grid(row=result_row+17, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#0FF").grid(row=result_row+18, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#0FF").grid(row=result_row+19, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+20, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+21, column=6, sticky=E)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+22, column=6, sticky=E)

#Column 7: ADC Current Measurements
w=Label(root, justify=RIGHT,text="I_meas").grid(row=result_row, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#0FF").grid(row=result_row+1, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+2, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+3, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+4, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+5, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+6, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+7, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+8, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+9, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+10, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+11, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+12, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+13, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+14, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+15, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+16, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+17, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#0FF").grid(row=result_row+18, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#0FF").grid(row=result_row+19, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+20, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+21, column=7)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+22, column=7)

#Column 8: DAC Voltage settings
w=Label(root, justify=RIGHT,text="V_set").grid(row=result_row, column=8)
txp_set = Entry(root, width=8)
txn_set = Entry(root, width=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+1, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+2, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+3, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+4, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+5, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+6, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+7, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+8, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+9, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+10, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+11, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+12, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+13, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+14, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+15, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+16, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+17, column=8)
txp_set.grid(row=result_row+18, column=8, sticky=W)
txn_set.grid(row=result_row+19, column=8, sticky=W)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+20, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+21, column=8)
w=Label(root, justify=RIGHT,width=8, relief=SUNKEN, bg="#DDD").grid(row=result_row+22, column=8)


#-------------------------------------------------------------
# secton for I/O board interface to Power Path and Charger
#-------------------------------------------------------------
io_row = 40

#w=Label(root, justify=LEFT, padx=10,text="----------------").grid(row=4, column=0)
ttk.Separator(root,orient=HORIZONTAL).grid(row=io_row, columnspan=8,sticky="ew")

w=Label(root, justify=LEFT, text="I/O Board Interface").grid(row=io_row+1, column=0, columnspan=3)


mainloop()
